version: '3.2'
services:

  security:
    build: ./APP-service
    ports:
     - "8080:8080"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./APP-service/src
  db:
    image: 'mysql:5.7'
    restart: always
    ports: 
        - "1246:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mock_api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - type: volume
        source: mysql_data
        target: /usr/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
volumes:
  mysql_data:
